#!/bin/bash

# Comments here

source ./vars &> /dev/null

while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

while [ -z "$BASTION_SEC_GRP_ID" ]; do
    BASTION_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$BASTION_SEC_GROUP" \
    --output text)
done

while [ -z "$MASTER_ELB_SEC_GRP_ID" ]; do
    MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$MASTER_ELB_SEC_GRP" \
    --output text)
done

while [ -z "$MASTER_SEC_GRP_ID" ]; do
    MASTER_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values=$MASTERS_SEC_GROUP \
    --output text)
done

# Create the application node security group
aws ec2 create-security-group \
--group-name $APP_NODES_SEC_GROUP \
--description "Security Group for OpenShift Application Nodes" \
--vpc-id $VPC_ID

while [ -z "$APP_NODES_SEC_GRP_ID" ]; do
    APP_NODES_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$APP_NODES_SEC_GROUP" \
    --output text)
done

aws ec2 create-tags \
--resources $APP_NODES_SEC_GRP_ID \
--tags Key=Name,Value=$APP_NODES_SEC_GROUP

aws ec2 authorize-security-group-ingress \
--group-id $APP_NODES_SEC_GRP_ID \
--protocol tcp \
--port 10250 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $APP_NODES_SEC_GRP_ID \
--protocol tcp \
--port 10255 \
--source-group $MASTER_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $APP_NODES_SEC_GRP_ID \
--protocol udp \
--port 10255 \
--source-group $MASTER_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $APP_NODES_SEC_GRP_ID \
--protocol udp \
--port 4789 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $APP_NODES_SEC_GRP_ID \
--protocol tcp \
--port 22 \
--source-group $BASTION_SEC_GRP_ID
