#!/bin/bash

# Comments here

source ./vars &> /dev/null

while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

# Create the bastion security group
aws ec2 create-security-group \
--group-name $BASTION_SEC_GROUP \
--description "Security Group for OpenShift Bastion" \
--vpc-id $VPC_ID

while [ -z "$BASTION_SEC_GRP_ID" ]; do
    BASTION_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$BASTION_SEC_GROUP" \
    --output text)
done

aws ec2 create-tags \
--resources $BASTION_SEC_GRP_ID \
--tags Key=Name,Value=$BASTION_SEC_GROUP

aws ec2 authorize-security-group-ingress \
--group-id $BASTION_SEC_GRP_ID \
--protocol tcp \
--port 22 \
--cidr 0.0.0.0/0

