#!/bin/bash

# Comments here

source ./vars &> /dev/null

while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

# Create the internal master ELB security group
aws ec2 create-security-group \
--group-name $INTERNAL_MASTER_ELB_SEC_GRP \
--description "Security Group for OpenShift Master ELB" \
--vpc-id $VPC_ID

while [ -z "$INTERNAL_INTERNAL_MASTER_ELB_SEC_GRP_ID" ]; do
    INTERNAL_INTERNAL_MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$INTERNAL_MASTER_ELB_SEC_GRP" \
    --output text)
done

aws ec2 create-tags \
--resources $INTERNAL_INTERNAL_MASTER_ELB_SEC_GRP_ID \
--tags Key=Name,Value=$INTERNAL_MASTER_ELB_SEC_GRP

aws ec2 authorize-security-group-ingress \
--group-id $INTERNAL_INTERNAL_MASTER_ELB_SEC_GRP_ID \
--protocol tcp \
--port 8443 \
--cidr 0.0.0.0/0
