#!/bin/bash

# Comments here

source ./vars &> /dev/null

VPC_ID=$(aws ec2 describe-vpcs \
--query Vpcs[].VpcId[] \
--filters Name=cidr,Values=$CIDR \
--output text)

BASTION_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values="$BASTION_SEC_GROUP" \
--output text)

MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values="$MASTER_ELB_SEC_GRP" \
--output text)

INTERNAL_MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values="$INTERNAL_MASTER_ELB_SEC_GRP" \
--output text)

# Create the master security group
aws ec2 create-security-group \
--group-name $MASTERS_SEC_GROUP \
--description "Security Group for OpenShift Master" \
--vpc-id $VPC_ID

MASTER_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values=$MASTERS_SEC_GROUP \
--output text)

aws ec2 create-tags \
--resources $MASTER_SEC_GRP_ID \
--tags Key=Name,Value=$MASTERS_SEC_GROUP

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 22 \
--source-group $BASTION_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 8443 \
--source-group $MASTER_ELB_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 8443 \
--source-group $INTERNAL_MASTER_ELB_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 8443 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 8444 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 8053 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol udp \
--port 8053 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol udp \
--port 4789 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 2379 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 10255 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol udp \
--port 10255 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 10250 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 9090 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 2380 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol udp \
--port 5404 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol udp \
--port 5405 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 2224 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 24224 \
--cidr $CIDR

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol udp \
--port 24224 \
--cidr $CIDR

