#!/bin/bash

# Comments here

source ./vars &> /dev/null

while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

# Create the router ELB security group
aws ec2 create-security-group \
--group-name $ROUTER_ELB_SEC_GRP \
--description "Security Group for OpenShift Router ELB" \
--vpc-id $VPC_ID

while [ -z "$ROUTER_ELB_SEC_GRP_ID" ]; do
    ROUTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$ROUTER_ELB_SEC_GRP" \
    --output text)
done

aws ec2 create-tags \
--resources $ROUTER_ELB_SEC_GRP_ID \
--tags Key=Name,Value=$ROUTER_ELB_SEC_GRP

aws ec2 authorize-security-group-ingress \
--group-id $ROUTER_ELB_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress \
--group-id $ROUTER_ELB_SEC_GRP_ID \
--protocol tcp \
--port 80 \
--cidr 0.0.0.0/0
