#!/bin/bash

TIMEOUT=60

# Set up path for var file so we can include it.
INCLUDE="$(dirname "$0")"

# Source Variables
source $INCLUDE/../vars &> /dev/null

# Get subnet id
while [ -z "$SUBNET_ID_4" ]; do
    SUBNET_ID_4=$(aws ec2 describe-subnets \
    --query Subnets[].SubnetId[] \
    --filters Name=cidr,Values=$SUBNET_CIDR_4 \
    --output text)
done

# Get security group id
while [ -z "$SEC_GROUP_ID" ]; do
    SEC_GROUP_ID=$(aws ec2 describe-security-groups \
    --query 'SecurityGroups[].GroupId[]' \
    --filters Name=group-name,Values=$BASTION_SEC_GROUP \
    --output text)
done

# Get vpc id
while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

# Launch AMI instance
aws ec2 run-instances \
--image-id $AMI_ID \
--count 1 \
--instance-type $BASTION_INSTANCE \
--key-name $KEY_NAME \
--security-group-ids $SEC_GROUP_ID \
--subnet-id $SUBNET_ID_4

# Query instances to get instance ID
while [ -z "$INSTANCE_ID" ]; do
    INSTANCE_ID=$(aws ec2 describe-instances \
    --query 'Reservations[].Instances[].[InstanceId]' \
    --filters "Name=instance-state-name,Values=running" "Name=instance.group-name,Values=$BASTION_SEC_GROUP" \
    --output text)
done

# Add tags
aws ec2 create-tags \
--resources $INSTANCE_ID \
--tags Key=Name,Value=$BASTION
