#!/bin/bash

TIMEOUT=60

# Set up path for var file so we can include it.
INCLUDE="$(dirname "$0")"

# Source Variables
source $INCLUDE/../vars &> /dev/null

# Query instances to get instance ID
INSTANCE_ID=$(aws ec2 describe-instances \
--query 'Reservations[].Instances[].[InstanceId]' \
--filters "Name=instance-state-name,Values=running" "Name=instance.group-name,Values=$BASTION_SEC_GROUP" \
--output text)

# Create EIP
EIP=$(aws ec2 allocate-address --domain vpc --output text | awk '{ print $1 }')

while [ "$BASTION_STATE" != "running" ]; do
    BASTION_STATE=$(aws ec2 describe-instances \
    --query 'Reservations[].Instances[].State[].Name[]' \
    --filters "Name=instance-state-name,Values=running" \
    "Name=tag:Name,Values=${UNIQ_VAR}-bastion.${INFRA_DNS}" \
    --output text)
done

# Associate EIP to instance
aws ec2 associate-address \
--instance-id $INSTANCE_ID \
--allocation-id $EIP
