#!/bin/bash

TIMEOUT=60

# Set up path for var file so we can include it.
INCLUDE="$(dirname "$0")"

# Source Variables
source $INCLUDE/../vars &> /dev/null

# Get the zone to put the bastion record in
while [ -z "$HOSTED_ZONE" ]; do
    HOSTED_ZONE=$(aws route53 list-hosted-zones-by-name \
    --dns-name=$INFRA_DNS --max-items=1 \
    --output text | awk '/HOSTED/ { print $3 }')
done

# Get vpc id
while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

# Query instances to get instance ID
while [ -z "$INSTANCE_ID" ]; do
    INSTANCE_ID=$(aws ec2 describe-instances \
    --query 'Reservations[].Instances[].[InstanceId]' \
    --filters "Name=instance-state-name,Values=running" "Name=instance.group-name,Values=$BASTION_SEC_GROUP" \
    --output text)
done

while [ -z "$BASTION_IP" ]; do
BASTION_IP=$(aws ec2 describe-instances \
--query Reservations[].Instances[].PublicIpAddress[] \
--filters "Name=tag:Name,Values=$BASTION" \
--output text)
done

sed -i \
-e "s/\"Value.*/\"Value\": \"$BASTION_IP\"/g" \
-e "s/\"Name.*/\"Name\": \"$BASTION\",/g" bastion/bastion-resource-record.json

# This json file is not applied yet, it is used by the terminate/delete-all script
sed -i \
-e "s/\"Value.*/\"Value\": \"$BASTION_IP\"/g" \
-e "s/\"Name.*/\"Name\": \"$BASTION\",/g" bastion/bastion-resource-record-terminate.json

# Create the A record.
aws route53 change-resource-record-sets \
--hosted-zone-id $HOSTED_ZONE \
--change-batch file://bastion/bastion-resource-record.json
