#!/bin/bash

# Source Variables
# source $INCLUDE/../vars
source ../vars &> /dev/null

# Set up path for var file so we can include it.
INCLUDE="$(dirname "$0")"

# Check for existance of jq package
if [[ ! -f /usr/bin/jq ]]
    then 
        echo
        echo "no jq package installed"
        echo "jq is needed to assign names to infra nodes during launch"
        echo
        exit
    else 
        echo "jq is installed"
fi

# Get security group id for nodes
SEC_GROUP_ID=$(aws ec2 describe-security-groups \
--query 'SecurityGroups[].GroupId[]' \
--filters Name=group-name,Values=$APP_NODES_SEC_GROUP \
--output text)

# Get vpc id
while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

# Get subnet id
while [ -z "$SUBNET_ID_1" ]; do
    SUBNET_ID_1=$(aws ec2 describe-subnets \
    --query Subnets[].SubnetId[] \
    --filters Name=cidr,Values=$SUBNET_CIDR_1 \
    --output text)
done

while [ -z "$SUBNET_ID_2" ]; do
    SUBNET_ID_2=$(aws ec2 describe-subnets \
    --query Subnets[].SubnetId[] \
    --filters Name=cidr,Values=$SUBNET_CIDR_2 \
    --output text)
done

# Create the instances and assign tags
aws ec2 create-tags \
--resources `aws ec2 run-instances \
--image-id $AMI_ID \
--instance-type $NODE_INST_TYPE \
--subnet-id $SUBNET_ID_1 \
--security-group-ids $SEC_GROUP_ID \
--block-device-mappings file://app-node/node-ebs-config.json \
--key-name $KEY_NAME --iam-instance-profile Name=$INSTANCE_PROFILE | jq -r ".Instances[0].InstanceId"` \
--tags "Key=Name,Value=$APP_NODE0" "Key=${KEY_TAG},Value=$APP_NODE_TAGS"

aws ec2 create-tags \
--resources `aws ec2 run-instances \
--image-id $AMI_ID \
--instance-type $NODE_INST_TYPE \
--subnet-id $SUBNET_ID_2 \
--security-group-ids $SEC_GROUP_ID \
--block-device-mappings file://app-node/node-ebs-config.json \
--key-name $KEY_NAME --iam-instance-profile Name=$INSTANCE_PROFILE | jq -r ".Instances[0].InstanceId"` \
--tags "Key=Name,Value=$APP_NODE1" "Key=${KEY_TAG},Value=$APP_NODE_TAGS"
