# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'socket'

hostname = Socket.gethostname
localmachineip = IPSocket.getaddress(Socket.gethostname)
puts %Q{ This machine has the IP '#{localmachineip} and host name '#{hostname}'}

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

deployment_type = ENV['DEPLOYMENT_TYPE'] || 'origin'

if deployment_type == 'enterprise'
  REQUIRED_PLUGINS = %w(vagrant-registration vagrant-hostmanager landrush)
else
  REQUIRED_PLUGINS = %w(vagrant-hostmanager landrush)
end

errors = []

def message(name)
  "#{name} plugin is not installed, run `vagrant plugin install #{name}` to install it."
end
# Validate and collect error message if plugin is not installed
REQUIRED_PLUGINS.each { |plugin| errors << message(plugin) unless Vagrant.has_plugin?(plugin) }
unless errors.empty?
  msg = errors.size > 1 ? "Errors: \n* #{errors.join("\n* ")}" : "Error: #{errors.first}"
  fail Vagrant::Errors::VagrantError.new, msg
end

if deployment_type == 'enterprise'
  box_name = 'rhel/7.2'
else
  box_name = 'centos/7'
end

NETWORK_BASE = '192.168.50'
INTEGRATION_START_SEGMENT = 20

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
#  config.hostmanager.include_offline = true
 
  config.landrush.enabled = true
  config.landrush.tld = 'example.com'
  config.landrush.guest_redirect_dns = false  

  if deployment_type == 'enterprise'
    # vagrant-registration
    if ENV.has_key?('SUB_USERNAME') && ENV.has_key?('SUB_PASSWORD')
      config.registration.username = ENV['SUB_USERNAME']
      config.registration.password = ENV['SUB_PASSWORD']
    end
    
    # Proxy Information from environment
    config.registration.proxy = PROXY = (ENV['PROXY'] || '')
    config.registration.proxyUser = PROXY_USER = (ENV['PROXY_USER'] || '')
    config.registration.proxyPassword = PROXY_PASSWORD = (ENV['PROXY_PASSWORD'] || '')
    config.registration.auto_attach = true
  end

  config.vm.provider "virtualbox" do |v|
     #v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//vagrant","1"]
     v.memory = 1024
     v.cpus = 1
  end

  config.vm.define :"master1.example.com" do |master1|
    master1.vm.box = box_name
    #master1.vm.box_url = centos_box_url
    master1.vm.network :private_network, ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT}"
    master1.vm.hostname = "master1.example.com"
  end

  config.vm.define :"node1.example.com" do |node1|
    node1.vm.box = box_name
    #node1.vm.box_url = centos_box_url
    node1.vm.network :private_network, ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT + 1}"
    node1.vm.hostname = "node1.example.com"
  end
 
  config.vm.define :"node2.example.com" do |node2|
    node2.vm.box = box_name
    #node2.vm.box_url = centos_box_url
    node2.vm.network :private_network, ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT + 2}"
    node2.vm.hostname = "node2.example.com"
  end

  config.vm.define :"admin1.example.com" do |admin1|
    admin1.vm.box = box_name
    #admin1.vm.box_url = centos_box_url
    admin1.vm.network :private_network, ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT + 3}"
    admin1.vm.hostname = "admin1.example.com"
    admin1.vm.synced_folder ".vagrant", "/vagrant_hidden", type: "rsync"

    if deployment_type == 'enterprise'
      admin1.vm.provision "shell", path: "enterprise_installer.sh"
    else
      admin1.vm.provision "shell", path: "origin_installer.sh"
    end

    admin1.vm.provision "shell", inline: "echo \"installing httpd-tools\""
    admin1.vm.provision "shell", inline: "sudo yum -y install httpd-tools"
    admin1.vm.provision "shell", path:"htpasswd.sh" 

    admin1.vm.provision :ansible_local do |ansible|
      ansible.verbose        = true
      ansible.install        = false
      ansible.limit          = ""
      ansible.inventory_path = "inventory"
      if deployment_type == 'enterprise'
        ansible.playbook = "/usr/share/ansible/openshift-ansible/playbooks/byo/config.yml"
        ansible.extra_vars = {
          deployment_type: "openshift-enterprise",
        }
      else
        ansible.playbook = "/home/vagrant/openshift-ansible/playbooks/byo/config.yml"
      end
    end
  end

  if deployment_type == 'enterprise'
    config.vm.provision "shell", inline: "echo \"setting up Red Hat subscriptions\""
    config.vm.provision "shell", path: "repos.sh"
  end
  config.vm.provision "shell", inline: "echo \"running install_helper_packages.sh\""
  config.vm.provision "shell", path: "install_helper_packages.sh"
  config.vm.provision "shell", inline: "echo \"running fix_hosts_file.sh\""
  config.vm.provision "shell", path: "fix_hosts_file.sh"

end
