---
- name: Launch instance
  ec2:
     keypair: "{{ keypair }}"
     group: ['ose_master_sg', 'ose_etcd_sg']
     instance_type: "{{ master_instance_type }}"
     image: "{{ ami }}"
     wait: true
     region: "{{ region }}"
     volumes:
       - device_name: /dev/sda1
         volume_type: gp2
         volume_size: 35
         delete_on_termination: true
       - device_name: /dev/xvdb
         volume_type: gp2
         volume_size: "{{ docker_storage }}"
         delete_on_termination: true
     vpc_subnet_id: "{{ private_subnet1 }}"
     instance_profile_name: ose-ebs
     instance_tags:
       Name: "{{ master_instance_prefix }}01.{{ public_hosted_zone }}"
       openshift-role: "{{ master_tag }}"
  register: master0
- name: Launch instance
  ec2:
     keypair: "{{ keypair }}"
     group: ose_master_sg
     instance_type: "{{ master_instance_type }}"
     image: "{{ ami }}"
     wait: true
     region: "{{ region }}"
     volumes:
       - device_name: /dev/sda1
         volume_type: gp2
         volume_size: 35
         delete_on_termination: true
       - device_name: /dev/xvdb
         volume_type: gp2
         volume_size: "{{ docker_storage }}"
         delete_on_termination: true
     vpc_subnet_id: "{{ private_subnet2 }}"
     instance_profile_name: ose-ebs
     instance_tags:
       Name: "{{ master_instance_prefix }}02.{{ public_hosted_zone }}"
       openshift-role: "{{ master_tag }}"
  register: master1
- name: Launch instance
  ec2:
     keypair: "{{ keypair }}"
     group: ose_master_sg
     instance_type: "{{ master_instance_type }}"
     image: "{{ ami }}"
     wait: true
     region: "{{ region }}"
     volumes:
       - device_name: /dev/sda1
         volume_type: gp2
         volume_size: 35
         delete_on_termination: true
       - device_name: /dev/xvdb
         volume_type: gp2
         volume_size: "{{ docker_storage }}"
         delete_on_termination: true
     vpc_subnet_id: "{{ private_subnet3 }}"
     instance_profile_name: ose-ebs
     instance_tags:
       Name: "{{ master_instance_prefix }}03.{{ public_hosted_zone }}"
       openshift-role: "{{ master_tag }}"
  register: master2
