#!/bin/bash

# Comments here

source ../vars &> /dev/null

# Grab the VPC ID for use later.
while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

# Create the dhcp options set.
aws ec2 create-dhcp-options \
--dhcp-configuration "Key=domain-name,Values=$DHCP_OPTS" "Key=domain-name-servers,Values=AmazonProvidedDNS" \
--query 'DhcpOptions.DhcpOptionsId' \
--output text > dhcp-opt

# Associate the dhcp option set to the VPC
aws ec2 associate-dhcp-options \
--dhcp-options-id $(cat dhcp-opt) \
--vpc-id $VPC_ID
