#!/bin/bash

LOGFILE=./deployment-logs/deploy-openshift-`hostname -s`-`date +%F_%T`.log

(

ECHO_STAGE() {
echo
echo
echo
echo "$1"
echo
echo
echo
}

# Confirm Internet Gateway has been created and attached

DEPLOY_VPC() {
ECHO_STAGE "deploying vpc"
sh -x ./vpc
}

DEPLOY_SSH_KEY() {
ECHO_STAGE "deploying ssh key"
sh -x ./ssh
}

DEPLOY_IAM() {
ECHO_STAGE "deploying iam roles"
pushd iam
sh -x ./iam-server
popd
}

DEPLOY_DNS_ZONES() {
ECHO_STAGE "deploying dns zones"
sh -x ./route53-zones
}

DEPLOY_SEC_GRPS() {
ECHO_STAGE "deploying security groups"
sh -x ./sec-groups/master-elb-sg
sh -x ./sec-groups/internal-master-elb-sg
sh -x ./sec-groups/bastion-sg
sh -x ./sec-groups/master-sg
sh -x ./sec-groups/router-elb-sg
sh -x ./sec-groups/node-sg
sh -x ./sec-groups/app-node-sg
}

DEPLOY_DHCP() {
ECHO_STAGE "deploying dhcp options"
pushd dhcp-config
sh -x ./dhcp
popd
}

DEPLOY_BASTION() {
ECHO_STAGE "deploying bastion host"
pushd bastion
sh -x ./bastion-instance-launch
sh -x ./bastion-eip
sh -x ./bastion-route53
popd
}

DEPLOY_MASTERS() {
ECHO_STAGE "deploying master nodes and configuring dns"
pushd master
sh -x ./masters-instance-launch
sh -x ./masters-route53
sh -x ./internal-masters-elb
sh -x ./internal-masters-elb-route53
sh -x ./masters-elb
sh -x ./masters-elb-route53
popd
}

DEPLOY_INFRA_NODES() {
ECHO_STAGE "deploying infrastructure nodes and configuring dns"
pushd infra-nodes
sh -x ./nodes-instance-launch
sh -x ./nodes-route53
popd
}

DEPLOY_APP_NODES() {
ECHO_STAGE "deploying application nodes and configuring dns"
pushd app-nodes
sh -x ./app-nodes-instance-launch
sh -x ./app-nodes-route53
popd
}

DEPLOY_ROUTER() {
ECHO_STAGE "deploying router"
pushd router-elb
sh -x ./router-elb
sh -x ./router-elb-route53
popd
}

# Call all functions for deployment
DEPLOY_VPC
DEPLOY_SSH_KEY
DEPLOY_IAM
DEPLOY_DNS_ZONES
DEPLOY_SEC_GRPS
DEPLOY_DHCP
DEPLOY_BASTION
DEPLOY_MASTERS
DEPLOY_INFRA_NODES
DEPLOY_APP_NODES
DEPLOY_ROUTER

) 2>&1 | tee ${LOGFILE}

echo
echo "Done with [openshift-deploy]. Wrote logfile: ${LOGFILE}"
echo
