#!/bin/bash

TIMEOUT=60

# # Set up path for var file so we can include it.
# INCLUDE="$(dirname "$0")"

# Source Variables
source ./vars &> /dev/null

# Check to see if the zone already exists
HOSTED_ZONE=$(aws route53 list-hosted-zones-by-name \
    --dns-name=$INFRA_DNS --output text --max-items=1 \
    | grep $INFRA_DNS | awk '/HOSTED/ { print $4 }')

if [ ! -z "$HOSTED_ZONE" ]; then
    echo "Skipping creation due to zone already existing"
else
    # Create the forward DNS zone, must provide a unique caller reference
    aws route53 create-hosted-zone \
    --name $INFRA_DNS \
    --caller-reference $(date "+%F-%H:%M:%S") \
    --hosted-zone-config Comment="Public hosted zone"
fi

# sleep 2 seconds to generate a different caller reference
sleep 2

# Check to see if the zone already exists
REVERSE_ZONE=$(aws route53 list-hosted-zones-by-name \
    --output text | grep $DNS_PTR \
    | awk '/HOSTED/ { print $4 }')

if [ ! -z "$REVERSE_ZONE" ]; then
    echo "Skipping creation due to zone already existing"
else
    # Create the reverse DNS zone
    aws route53 create-hosted-zone \
    --name $DNS_PTR \
    --caller-reference $(date "+%F-%H:%M:%S") \
    --hosted-zone-config Comment="Reverse hosted zone"
fi
