# -*- mode: ruby -*-
# vi: set ft=ruby :
# 

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
VAGRANTFILE_API_VERSION = "2"

if ARGV.first == "up" && ENV.include?('AWS_ACCESS_KEY_ID') == false && ENV.include?('AWS_SECRET_ACCESS_KEY') == false
  raise Vagrant::Errors::VagrantError.new, <<END
Please export EC2 credentials AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY before attemping to run the provision scripts.
END
end

if ARGV.first == "up" && ENV.include?('PUBLIC_HOSTED_ZONE') == false
  raise Vagrant::Errors::VagrantError.new, <<END
Please export PUBLIC_HOSTED_ZONE.
END
end

$provision = <<SCRIPT
#!/bin/bash
set -e

rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# Install dependencies
yum -y install python-pip git python2-boto \
                python-netaddr python-httplib2 python-devel \
                gcc libffi-devel openssl-devel python2-boto3 \
                python-click python-six pyOpenSSL httpd-tools \
                java-1.8.0-openjdk-headless python-passlib

# Upgrade pip
pip install --upgrade pip

# Install ansible v2.2, setuptools and graffiti_monkey
pip install --upgrade git+git://github.com/ansible/ansible.git@stable-2.2 setuptools graffiti_monkey -vvv

# Clone repository 
mkdir -p /usr/share/ansible
cd /usr/share/ansible
git clone https://github.com/openshift/openshift-ansible.git openshift-ansible 
cd openshift-ansible && git checkout release-3.7
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dummy"
  
  # set auto_update to false, if you do NOT want to check the correct 
  # additions version when booting this machine
  config.vbguest.auto_update = false

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.region = "us-east-2"

    # TODO: map CentOS 7 AMI - This is valid for eu-west-2
    aws.ami = "ami-9cbf9bf9"
    aws.instance_type = "t2.medium"
    aws.keypair_name = "management-ocp"
    aws.iam_instance_profile_name = "management-ocp-role"

    aws.user_data = $provision

    aws.tags = {
      "Name" => "management.#{ENV['PUBLIC_HOSTED_ZONE']}"
    }

    override.ssh.username = "centos"
    override.ssh.private_key_path = "~/.ssh/management-ocp.pem"
    override.ssh.forward_agent = true
  end

  config.vm.synced_folder "../../", "/usr/src/openshift-ansible", type: "rsync",
    rsync__exclude: ".git/"
end
