---
- name: Create production VMs on vCenter
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    guest: "{{ item.value.guestname }}"
    cluster: "{{ vcenter_cluster}}"
    resource_pool: "{{ vcenter_resource_pool }}"
    from_template: yes
    template_src: "{{vcenter_template_name}}"
    power_on_after_clone: true
    vm_extra_config:
      folder: "{{ vcenter_folder }}"
      notes: "{{ item.value.tag }}"
  with_dict: "{{ production_hosts }}"

- name: Get facts of production VMs
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    vmware_guest_facts: yes
    guest: "{{ item.value.guestname }}"
  register: actual_production_hosts
  with_dict: "{{ production_hosts }}"
  until:  actual_production_hosts.ansible_facts.hw_eth0.ipaddresses[0] is defined
  retries: 10
  delay: 10

- name: Add production VMs to inventory
  add_host: hostname={{item.ansible_facts.hw_name}} ansible_ssh_host={{item.ansible_facts.hw_eth0.ipaddresses[0]}} groups="production_group, {{ item.item.value.tag }}"
  with_items: "{{ actual_production_hosts.results }}"
  ignore_errors: yes

- name: Add production VMs to inventory
  add_host: hostname={{item.ansible_facts.hw_name}} ansible_ssh_host={{item.ansible_facts.hw_eth0.ipaddresses[1]}} groups="production_group, {{ item.item.value.tag }}"
  with_items: "{{ actual_production_hosts.results }}"
  when: actual_testing_hosts.ansible_facts.hw_eth0.ipaddresses[1] is defined
  ignore_errors: yes
