#!/bin/bash

# Comments here

# Source Variables
source ../vars &> /dev/null

# Grab master ELB name
while [ -z "$INTERNAL_MASTER_ELB" ]; do
    INTERNAL_MASTER_ELB=$(aws elb describe-load-balancers \
    --query 'LoadBalancerDescriptions[].DNSName[]' \
    | grep ${INTERNAL_MASTER_LB_NAME} | tr -d '"' | tr -d ',' | tr -d ' ')
done

# Set up Route53 record
while [ -z "$HOSTED_ZONE" ]; do
    HOSTED_ZONE=$(aws route53 list-hosted-zones-by-name \
    --dns-name=$INFRA_DNS --max-items=1\
    --output text | awk '/HOSTED/ { print $3 }')
done

sed -i \
    -e "s/\"Value.*/\"Value\": \"$INTERNAL_MASTER_ELB\"/g" \
    -e "s/\"Name.*/\"Name\": \"$INTERNAL_MASTER_ELB_CNAME\",/g" master/internal-master-elb-a-record.json

sed -i \
    -e "s/\"Value.*/\"Value\": \"$INTERNAL_MASTER_ELB\"/g" \
    -e "s/\"Name.*/\"Name\": \"$INTERNAL_MASTER_ELB_CNAME\",/g" master/internal-master-elb-a-record-terminate.json

aws route53 change-resource-record-sets \
--hosted-zone-id $HOSTED_ZONE \
--change-batch file://master/internal-master-elb-a-record.json
