#!/bin/bash

# Comments here

# Source Variables
source ../vars &> /dev/null

# Query the deployed instance for it's private IP, assign to a variable.  Then add this entry to the json file that creates the record.
while [ -z "$MASTER00_IP" ]; do
    MASTER00_IP=$(aws ec2 describe-instances \
    --query Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress[] \
    --filters "Name=tag:Name,Values=${UNIQ_VAR}-master00.*" \
    --output text)
done

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER00_IP\"/g" \
-e "s/\"Name.*/\"Name\": \"$MASTER0\",/g" master/master00-a-record.json

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER00_IP\"/g" \
-e "s/\"Name.*/\"Name\": \"$MASTER0\",/g" master/master00-a-record-terminate.json

while [ -z "$MASTER01_IP" ]; do
    MASTER01_IP=$(aws ec2 describe-instances \
    --query Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress[] \
    --filters "Name=tag:Name,Values=${UNIQ_VAR}-master01.*" \
    --output text)
done

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER01_IP\"/g" \
-e "s/\"Name.*/\"Name\": \"$MASTER1\",/g" master/master01-a-record.json

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER01_IP\"/g" \
-e "s/\"Name.*/\"Name\": \"$MASTER1\",/g" master/master01-a-record-terminate.json

while [ -z "$MASTER02_IP" ]; do
    MASTER02_IP=$(aws ec2 describe-instances \
    --query Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress[] \
    --filters "Name=tag:Name,Values=${UNIQ_VAR}-master02.*" \
    --output text)
done

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER02_IP\"/g" \
-e "s/\"Name.*/\"Name\": \"$MASTER2\",/g" master/master02-a-record.json

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER02_IP\"/g" \
-e "s/\"Name.*/\"Name\": \"$MASTER2\",/g" master/master02-a-record-terminate.json

# Set up Route53 A records
while [ -z "$HOSTED_ZONE" ]; do
    HOSTED_ZONE=$(aws route53 list-hosted-zones-by-name \
    --dns-name=$INFRA_DNS --max-items=1 \
    --output text | awk '/HOSTED/ { print $3 }')
done

aws route53 change-resource-record-sets \
--hosted-zone-id $HOSTED_ZONE \
--change-batch file://master/master00-a-record.json

aws route53 change-resource-record-sets \
--hosted-zone-id $HOSTED_ZONE \
--change-batch file://master/master01-a-record.json

aws route53 change-resource-record-sets \
--hosted-zone-id $HOSTED_ZONE \
--change-batch file://master/master02-a-record.json

# Set up PTR records in DNS

while [ -z "$REV_HOSTED_ZONE" ]; do
    REV_HOSTED_ZONE=$(aws route53 list-hosted-zones-by-name \
    --dns-name=$DNS_PTR --max-items=1 \
    --output text | awk '/HOSTED/ { print $3 }')
done

# Need to reverse those IPs for reverse DNS
REV_DNS0=$(echo "$MASTER00_IP" | awk -F. '{print $4"."$3"."$2"."$1".in-addr.arpa"}')
REV_DNS1=$(echo "$MASTER01_IP" | awk -F. '{print $4"."$3"."$2"."$1".in-addr.arpa"}')
REV_DNS2=$(echo "$MASTER02_IP" | awk -F. '{print $4"."$3"."$2"."$1".in-addr.arpa"}')

# Configure the json files with the appropriate entries
sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER0\"/g" \
-e "s/\"Name.*/\"Name\": \"$REV_DNS0\",/g" master/master00-ptr-record.json

# These terminate files are used for deleting the environment later
sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER0\"/g" \
-e "s/\"Name.*/\"Name\": \"$REV_DNS0\",/g" master/master00-ptr-record-terminate.json

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER1\"/g" \
-e "s/\"Name.*/\"Name\": \"$REV_DNS1\",/g" master/master01-ptr-record.json

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER1\"/g" \
-e "s/\"Name.*/\"Name\": \"$REV_DNS1\",/g" master/master01-ptr-record-terminate.json

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER2\"/g" \
-e "s/\"Name.*/\"Name\": \"$REV_DNS2\",/g" master/master02-ptr-record.json

sed -i \
-e "s/\"Value.*/\"Value\": \"$MASTER2\"/g" \
-e "s/\"Name.*/\"Name\": \"$REV_DNS2\",/g" master/master02-ptr-record-terminate.json

# Deploy the PTR records
aws route53 change-resource-record-sets \
--hosted-zone-id $REV_HOSTED_ZONE \
--change-batch file://master/master00-ptr-record.json

aws route53 change-resource-record-sets \
--hosted-zone-id $REV_HOSTED_ZONE \
--change-batch file://master/master01-ptr-record.json

aws route53 change-resource-record-sets \
--hosted-zone-id $REV_HOSTED_ZONE \
--change-batch file://master/master02-ptr-record.json
