#!/bin/bash

# Comments here

# Set up path for var file so we can include it.
INCLUDE="$(dirname "$0")"

# Check for existance of jq package
if [[ ! -f /usr/bin/jq ]]
    then 
        echo
        echo "no jq package installed"
        echo "jq is needed to assign names to masters during launch"
        echo
        exit
    else 
        echo "jq is installed"
fi

# Source Variables
source $INCLUDE/../vars &> /dev/null

# Get security group id
while [ -z "$SEC_GROUP_ID" ]; do
    SEC_GROUP_ID=$(aws ec2 describe-security-groups \
    --query 'SecurityGroups[].GroupId[]' \
    --filters Name=group-name,Values=$MASTERS_SEC_GROUP \
    --output text)
done

# Get vpc id
while [ -z "$VPC_ID" ]; do
    VPC_ID=$(aws ec2 describe-vpcs \
    --query Vpcs[].VpcId[] \
    --filters Name=cidr,Values=$CIDR \
    --output text)
done

# Get subnet id
while [ -z "$SUBNET_ID_1" ]; do
    SUBNET_ID_1=$(aws ec2 describe-subnets \
    --query Subnets[].SubnetId[] \
    --filters Name=cidr,Values=$SUBNET_CIDR_1 \
    --output text)
done

while [ -z "$SUBNET_ID_2" ]; do
    SUBNET_ID_2=$(aws ec2 describe-subnets \
    --query Subnets[].SubnetId[] \
    --filters Name=cidr,Values=$SUBNET_CIDR_2 \
    --output text)
done

while [ -z "$SUBNET_ID_3" ]; do
    SUBNET_ID_3=$(aws ec2 describe-subnets \
    --query Subnets[].SubnetId[] \
    --filters Name=cidr,Values=$SUBNET_CIDR_3 \
    --output text)
done

# Deploy the instances and assign the tags
aws ec2 create-tags \
--resources `aws ec2 run-instances \
--image-id $AMI_ID \
--instance-type $MASTER_INST_TYPE \
--subnet-id $SUBNET_ID_1 \
--security-group-ids $SEC_GROUP_ID \
--block-device-mappings file://master/master-ebs-config.json \
--key-name $KEY_NAME --iam-instance-profile Name=$INSTANCE_PROFILE | jq -r ".Instances[0].InstanceId"` \
--tags "Key=Name,Value=$MASTER0" "Key=${KEY_TAG},Value=$MASTER_NODE_TAGS"

aws ec2 create-tags \
--resources `aws ec2 run-instances \
--image-id $AMI_ID \
--instance-type $MASTER_INST_TYPE \
--subnet-id $SUBNET_ID_2 \
--security-group-ids $SEC_GROUP_ID \
--block-device-mappings file://master/master-ebs-config.json \
--key-name $KEY_NAME --iam-instance-profile Name=$INSTANCE_PROFILE | jq -r ".Instances[0].InstanceId"` \
--tags "Key=Name,Value=$MASTER1" "Key=${KEY_TAG},Value=$MASTER_NODE_TAGS"

aws ec2 create-tags \
--resources `aws ec2 run-instances \
--image-id $AMI_ID \
--instance-type $MASTER_INST_TYPE \
--subnet-id $SUBNET_ID_3 \
--security-group-ids $SEC_GROUP_ID \
--block-device-mappings file://master/master-ebs-config.json \
--key-name $KEY_NAME --iam-instance-profile Name=$INSTANCE_PROFILE | jq -r ".Instances[0].InstanceId"` \
--tags "Key=Name,Value=$MASTER2" "Key=${KEY_TAG},Value=$MASTER_NODE_TAGS"
