# vim: set ft=ansible:
---
- name: 'Tearing Down an Environment'
  hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  vars_files:
  - vars.yml
  tasks:
  - name: 'Validating options'
    fail:
      msg: required values not set
    when: >
      cluster_id is not defined
      or env_id is not defined

  - name: Teardown CloudFormation Template
    cloudformation:
      region: "{{ ec2_region }}"
      stack_name: openshift-{{ cluster_id }}-{{ env_id }}
      state: absent
      template: files/cloudformation.json
