#!/bin/bash

# Comments here
INCLUDE="$(dirname "$0")"

# Source Variables
source $INCLUDE/../vars &> /dev/null

# Create the policy
while [ -z "$POLICY" ]; do
    POLICY=$(aws iam create-policy \
    --policy-name $IAM_POLICY_NAME \
    --policy-document file://EBSServerRolePolicy.json --output text)
done

# Grab the policy arn
while [ -z "$POL_ARN" ]; do
    POL_ARN=$(echo $POLICY | awk '{ print $2 }')
done

# Write the arn down for teardown later, this can be removed from prod scripts, scollier 5/6/2016
echo $POL_ARN > pol_arn

# Create the role
aws iam create-role \
--role-name $IAM_ROLE_NAME \
--assume-role-policy-document file://EBSServerRole.json

# Attach the role to a policy
aws iam attach-role-policy \
--role-name $IAM_ROLE_NAME \
--policy-arn $POL_ARN

# Create the instance profile
aws iam create-instance-profile \
--instance-profile-name $INSTANCE_PROFILE


# Add the role to the instance profile
aws iam add-role-to-instance-profile \
--instance-profile-name $INSTANCE_PROFILE \
--role-name $IAM_ROLE_NAME 
