#!/bin/bash

# Comments here

source ../vars &> /dev/null

# Get subnets to add to load balancer
while [ -z "$SUBNET_ID_4" ]; do
    SUBNET_ID_4=$(aws ec2 describe-subnets \
    --query Subnets[].SubnetId[] \
    --filters Name=cidr,Values=$SUBNET_CIDR_4 \
    --output text)
done

while [ -z "$SUBNET_ID_5" ]; do
SUBNET_ID_5=$(aws ec2 describe-subnets \
    --query Subnets[].SubnetId[] \
    --filters Name=cidr,Values=$SUBNET_CIDR_5 \
    --output text)
done

# Get instances to add to load balancer
while [ -z "$INSTANCE_ID_1" ]; do
    INSTANCE_ID_1=$(aws ec2 describe-instances \
    --query 'Reservations[].Instances[].[InstanceId]' \
    --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-node00.*" \
    --output text)
done

while [ -z "$INSTANCE_ID_2" ]; do
    INSTANCE_ID_2=$(aws ec2 describe-instances \
    --query 'Reservations[].Instances[].[InstanceId]' \
    --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-node01.*" \
    --output text)
done

# Create load balancer for masters
aws elb create-load-balancer \
--load-balancer-name $ROUTER_LB_NAME \
--listeners "Protocol=TCP,LoadBalancerPort=80,InstancePort=80" \
--subnets "$SUBNET_ID_4" "$SUBNET_ID_5"

# Add load balancer to security group
while [ -z "$ROUTER_ELB_SEC_GRP_ID" ]; do
    ROUTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$ROUTER_ELB_SEC_GRP" \
    --output text)
done

aws elb apply-security-groups-to-load-balancer \
--load-balancer-name $ROUTER_LB_NAME \
--security-groups $ROUTER_ELB_SEC_GRP_ID

# set up health check
aws elb configure-health-check \
--load-balancer-name $ROUTER_LB_NAME \
--health-check Target=tcp:443,Interval=5,UnhealthyThreshold=2,HealthyThreshold=2,Timeout=2

# add nodes to load balancer
aws elb register-instances-with-load-balancer \
--load-balancer-name $ROUTER_LB_NAME \
--instances $INSTANCE_ID_1 $INSTANCE_ID_2 $INSTANCE_ID_3

# Enable cross AZ Load Balancing
aws elb modify-load-balancer-attributes --load-balancer-name \
$ROUTER_LB_NAME --load-balancer-attributes \
"{\"CrossZoneLoadBalancing\":{\"Enabled\":true}}"
