#!/bin/bash

# Comments here

# Source Variables
source ../vars &> /dev/null

# Get the ELB router id
while [ -z "$ROUTER_ELB" ]; do
    ROUTER_ELB=$(aws elb describe-load-balancers \
    --query 'LoadBalancerDescriptions[].DNSName[]' \
    | grep $ROUTER_LB_NAME | tr -d '"' | tr -d ',' | tr -d ' ')
done

# Set up Route53 A record
while [ -z "$HOSTED_ZONE" ]; do
    HOSTED_ZONE=$(aws route53 list-hosted-zones-by-name \
    --dns-name=$INFRA_DNS --max-items=1\
    --output text | awk '/HOSTED/ { print $3 }')
done

sed -i \
-e "s/\"Value.*/\"Value\": \"$ROUTER_ELB\"/g" \
-e "s/\"Name.*/\"Name\": \"$ROUTER_ELB_CNAME\",/g" router-elb-a-record.json

sed -i \
-e "s/\"Value.*/\"Value\": \"$ROUTER_ELB\"/g" \
-e "s/\"Name.*/\"Name\": \"$ROUTER_ELB_CNAME\",/g" router-elb-a-record-terminate.json

# Deploy the A record in DNS
aws route53 change-resource-record-sets \
--hosted-zone-id $HOSTED_ZONE \
--change-batch file://router-elb-a-record.json
